print("-------------------------------")
print("|        NOT         |  True? |")
print("-------------------------------")
print("|     not False      |  True  |")
print("-------------------------------")
print("                               ")
print("-------------------------------")
print("|        NOT         |  True? |")
print("-------------------------------")
print("|     not False      |  False |")
print("-------------------------------")
print("                               ")
print("-------------------------------")
print("|        OR          |  True? |")
print("-------------------------------")
print("|   True or False    |  True  |")
print("-------------------------------")
print("|   True or True     |  True  |")
print("-------------------------------")
print("|   False or True    |  True  |")
print("-------------------------------")
print("|   False or True    |  False |")
print("-------------------------------")
print("                               ")
print("-------------------------------")
print("|        AND         |  True? |")
print("-------------------------------")
print("|   True and False   |  False |")
print("-------------------------------")
print("|   True and True    |  True  |")
print("-------------------------------")
print("|   False and True   |  False |")
print("-------------------------------")
print("|   False and False  |  False |")
print("-------------------------------")
print("                               ")
print("-------------------------------")
print("|      NOT OR        |  True? |")
print("-------------------------------")
print("|not(True or False)  |  False |")
print("-------------------------------")
print("|not(True or True)   |  False |")
print("-------------------------------")
print("|not(False or True)  |  False |")
print("-------------------------------")
print("|not(False or Fasel) |  True  |")
print("-------------------------------")
print("                               ")
print("-------------------------------")
print("|       NOT AND      |  True? |")
print("-------------------------------")
print("|not(True and False) |  True  |")
print("-------------------------------")
print("|not(True and True)  |  False |")
print("-------------------------------")
print("|not(False and True) |  True  |")
print("-------------------------------")
print("|not(False and False)|  True  |")
print("-------------------------------")
print("                               ")
print("-------------------------------")
print("|         !=          | True? |")
print("-------------------------------")
print("|       1 != 0        | True  |")
print("-------------------------------")
print("|       1 != 1        | False |")
print("-------------------------------")
print("|       0 != 1        | True  |")
print("-------------------------------")
print("|       0 != 0        | False |")
print("-------------------------------")
print("                               ")
print("-------------------------------")
print("|         ==          | True? |")
print("-------------------------------")
print("|       1 == 0        | False |")
print("-------------------------------")
print("|       1 == 1        | True  |")
print("-------------------------------")
print("|       0 == 1        | False |")
print("-------------------------------")
print("|       0 == 0        | True  |")
print("-------------------------------")

